(() => {
  'use strict';
  const CONFIG = {
    counterBase:'https://countapi.mileshilliard.com/api/v1',
    baselineUrl:'https://raw.githubusercontent.com/emrepelit109/science-philosophy/main/stats/read-baseline.json',
    counters:{
      bloggerNet:'science-philosophy-blogger-new-post-reads-2026-09-30-b4e71c',
      bloggerViews:'science-philosophy-blogger-page-views-2026-09-30-c73a2d',
      sourceNet:'science-philosophy-grokme-web-reads-2026-09-26-7c2f9a',
      sourceViews:'science-philosophy-grokme-page-views-2026-09-26-8e4d1c',
      pagesNet:'science-philosophy-github-pages-web-reads-2026-09-26-41a6d2',
      pagesViews:'science-philosophy-github-pages-page-views-2026-09-26-5b7a2e',
      appNet:'science-philosophy-grokme-app-reads-2026-09-30-a91f4e'
    },
    minimumReadSeconds:10, perPagePerDay:true, refreshMs:30000
  };
  const nf=new Intl.NumberFormat('tr-TR');
  async function json(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
  function hostType(){const h=location.hostname;if(h==='emrepelit7337.blogspot.com'||h.endsWith('.blogspot.com'))return'blogger';if(h==='science-philosophy.grok.me'||h==='www.science-philosophy.grok.me')return'source';if(h==='emrepelit109.github.io')return'pages';return null}
  function keyFor(kind){const t=hostType();return t?CONFIG.counters[t+(kind==='views'?'Views':'Net')]:null}
  function storageKey(){return'sp:netread:'+new Date().toISOString().slice(0,10)+':'+(location.pathname||'/')}
  function alreadyRead(){try{return localStorage.getItem(storageKey())==='1'}catch(_){return false}}
  function markRead(){try{localStorage.setItem(storageKey(),'1')}catch(_){}}
  async function hit(kind){const k=keyFor(kind);if(!k)return null;const j=await json(CONFIG.counterBase+'/hit/'+encodeURIComponent(k));return Number(j.value)||0}
  async function getCounter(k){try{const j=await json(CONFIG.counterBase+'/get/'+encodeURIComponent(k));return Number(j.value)||0}catch(_){return 0}}
  function initTracking(){if(window.__spTrackingStarted||!hostType())return;window.__spTrackingStarted=true;hit('views').catch(()=>{});if(alreadyRead())return;let started=Date.now(),acc=0,timer=null,counted=false;function count(){if(counted||alreadyRead()||document.hidden)return;counted=true;hit('net').then(markRead).catch(()=>counted=false)}function schedule(){if(timer)clearTimeout(timer);timer=setTimeout(count,Math.max(0,CONFIG.minimumReadSeconds*1000-acc))}document.addEventListener('visibilitychange',()=>{if(document.hidden){acc+=Date.now()-started;if(timer)clearTimeout(timer);timer=null}else{started=Date.now();if(acc>=CONFIG.minimumReadSeconds*1000)count();else schedule()}},{passive:true});schedule()}
  function addStyle(){if(document.getElementById('sp-live-style'))return;const s=document.createElement('style');s.id='sp-live-style';s.textContent='#sp-live-root{position:fixed;right:18px;bottom:18px;z-index:2147483647;font-family:system-ui,-apple-system,Segoe UI,sans-serif}#sp-live-toggle{border:0;border-radius:999px;padding:12px 16px;background:#111827;color:#fff;font-weight:800;box-shadow:0 8px 28px #0005;cursor:pointer;border:1px solid #3b82f6}#sp-live-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#28d17c;margin-right:8px}#sp-live-panel{display:none;width:min(440px,calc(100vw - 36px));margin-bottom:10px;background:#0f1629;color:#eef2ff;border:1px solid #34446e;border-radius:16px;padding:14px;box-shadow:0 16px 45px #0007}#sp-live-panel.open{display:block}#sp-live-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:10px}.sp-live-stat{padding:10px;border:1px solid #263555;border-radius:10px;background:#121b30}.sp-live-stat small{display:block;color:#aeb9d6;font-size:.74rem}.sp-live-stat strong{display:block;margin-top:3px;font-size:1rem}#sp-live-note{margin-top:10px;color:#aeb9d6;font-size:.78rem;line-height:1.45}#sp-live-refresh{margin-top:10px;width:100%;border:1px solid #34446e;background:#1d2945;color:#dfe8ff;border-radius:10px;padding:9px 12px;font-weight:700;cursor:pointer}';document.head.appendChild(s)}
  async function load(panel,status,refresh){
    // Stats updates must stay local to the Live Stats panel. Never invalidate/remount
    // the page-level data tree here; doing so can reset the document scroll position.
    const scrollX=window.scrollX,scrollY=window.scrollY;
    refresh.disabled=true;status.textContent='Veriler alınıyor…';try{const[b,vals]=await Promise.all([json(CONFIG.baselineUrl+'?ts='+Date.now()).catch(()=>({})),Promise.all([getCounter(CONFIG.counters.bloggerNet),getCounter(CONFIG.counters.bloggerViews),getCounter(CONFIG.counters.sourceNet),getCounter(CONFIG.counters.sourceViews),getCounter(CONFIG.counters.pagesNet),getCounter(CONFIG.counters.pagesViews),getCounter(CONFIG.counters.appNet)])]);const[bn,bv,sn,sv,pn,pv,an]=vals;const bloggerNet=Number(b.blogger_post_reads_baseline||0)+bn,websiteNet=Number(b.website_web_reads_baseline||0)+sn,pagesNet=Number(b.github_pages_net_read_baseline||0)+pn,appNet=Number(b.website_app_reads_baseline||0)+an,totalNet=bloggerNet+websiteNet+pagesNet+appNet,bloggerViews=Number(b.blogger_page_views_baseline||0)+bv,websiteViews=Number(b.website_page_views_baseline||0)+sv,pagesViews=Number(b.github_pages_page_views_baseline||0)+pv,totalViews=bloggerViews+websiteViews+pagesViews;panel.innerHTML='<strong>Science & Philosophy — Live Stats</strong><div id="sp-live-grid"><div class="sp-live-stat"><small>Blogger okunmaları</small><strong>'+nf.format(bloggerNet)+'</strong></div><div class="sp-live-stat"><small>Website net okunma</small><strong>'+nf.format(websiteNet)+'</strong></div><div class="sp-live-stat"><small>GitHub Pages okunma</small><strong>'+nf.format(pagesNet)+'</strong></div><div class="sp-live-stat"><small>Uygulama okunmaları</small><strong>'+nf.format(appNet)+'</strong></div><div class="sp-live-stat"><small>BİRLEŞİK NET OKUNMA</small><strong>'+nf.format(totalNet)+'</strong></div><div class="sp-live-stat"><small>TOPLAM GÖRÜNTÜLEME</small><strong>'+nf.format(totalViews)+'</strong></div></div><div id="sp-live-note"><strong>Net okuma:</strong> en az 10 saniye görünür kalırsa +1.<br><strong>Görüntüleme:</strong> sayfa açılışında +1.<br><strong>21.839:</strong> artık hiçbir hesaba eklenmiyor.</div>';status.textContent='● CANLI · '+new Date().toLocaleTimeString('tr-TR');status.style.color='#28d17c'}catch(_){panel.innerHTML='<div>Canlı istatistikler şu anda alınamadı.</div>';status.textContent='● HATA'}finally{refresh.disabled=false;requestAnimationFrame(()=>{window.scrollTo({left:scrollX,top:scrollY,behavior:'auto'})})}}
  function mount(){if(document.getElementById('sp-live-root'))return;addStyle();initTracking();const root=document.createElement('div');root.id='sp-live-root';root.innerHTML='<div id="sp-live-panel"><div id="sp-live-status">Hazır</div><button id="sp-live-refresh" type="button">↻ Yenile</button></div><button id="sp-live-toggle" type="button"><span id="sp-live-dot"></span>Live Stats</button>';document.body.appendChild(root);const panel=root.querySelector('#sp-live-panel'),toggle=root.querySelector('#sp-live-toggle'),refresh=root.querySelector('#sp-live-refresh'),status=root.querySelector('#sp-live-status');toggle.addEventListener('click',()=>{const open=panel.classList.toggle('open');if(open)load(panel,status,refresh)});refresh.addEventListener('click',()=>load(panel,status,refresh));setInterval(()=>{if(panel.classList.contains('open'))load(panel,status,refresh)},CONFIG.refreshMs)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();window.SciencePhilosophyLiveStats={mount};
})();